{% set name = "pysaml2" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysaml2-{{ version }}.tar.gz
  sha256: 6d446de515dcb3a88ac52f2679cc7c6c46362239dbec94996d78168ac30ee3d4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography >=1.4
    - defusedxml
    - pyopenssl
    - python >=3.6
    - python-dateutil
    - pytz
    - requests >=1.0.0
    - six

test:
  imports:
    - saml2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://idpy.org
  summary: Python implementation of SAML Version 2 Standard
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
